[build-system]
requires = [
    'setuptools>=42',
    'wheel',
    'setuptools_scm[toml]>=3.4',
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.setuptools_scm]
fallback_version = '2.0.0'
local_scheme = 'dirty-tag'
write_to = '_version.py'
