common:
  hubname: demo
  directory: ~/genomehubs/demo
  docker-network: genomehubs-network
  es:
    host: localhost
    port: 9200
  taxonomy:
    sources:
      - ncbi
  version: v0.1
index:
  insdc:
    page-size: 1000
    genome-representation: full
  skip-validation: false
init:
  es:
    container: genomehubs-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    startup-timeout: 30
    url: https://artifacts.elastic.co/downloads
  taxonomy:
    path: ~/genomehubs/demo/taxdump
    ncbi:
      root: 1
      url: ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
  use-docker: false
search: {}
