common:
  docker:
    network: genomehubs-demo-network
  es:
    host:
      - localhost:9200
  hub:
    name: demo
    path: ~/genomehubs/demo
    version: v0.1
  taxonomy:
    sources:
      - ncbi
index:
  insdc:
    genome-representation: full
    page-size: 1000
  skip-validation: false
init:
  docker:
    contain: []
    es:
      container: ghubs-es
      image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2"
    timeout: 30
  es:
    url: "https://artifacts.elastic.co/downloads"
  taxonomy:
    ncbi:
      root: 1
      url: "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"
    path: ~/genomehubs/demo/taxdump
search: {}
