common:
  # docker:
  #   contain: []
  #   es:
  #     container: ghubs-es
  #     image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1"
  #   network: genomehubs-demo-network
  #   timeout: 30
  es:
    batch: 500
    host:
      - "localhost:9200"
    path: ~/genomehubs/demo_resources/es
    timeout: 30
    url: "https://artifacts.elastic.co/downloads/elasticsearch"
    version: elasticsearch-oss-7.8.1
  hub:
    name: demo
    path: ~/genomehubs/demo
    separator: "--"
    version: v0.1
fill: {}
index: {}
init: {}
# docker:
#   contain: []
#   es:
#     container: ghubs-es
#     image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1"
#   timeout: 30
# es:
#   path: ~/genomehubs/demo_resources/es
#   timeout: 30
#   url: "https://artifacts.elastic.co/downloads/elasticsearch"
#   version: elasticsearch-oss-7.8.1
# taxonomy:
#   ncbi:
#     file:
#       - nodes.dmp
#       - names.dmp
#     url: "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"
#   path: ~/genomehubs/demo_resources/taxdump
parse: {}
test: {}
