{% set name = "genomehubs" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/genomehubs/genomehubs.git

build:
  number: 0
  entry_points:
    - genomehubs = genomehubs:cli
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - biopython>=1.78
    - docopt>=0.6.2
    - elasticsearch>=7.8.1
    - filetype>=1.0.7
    - pip
    - Pillow>=8.0
    - python
    - pyyaml
    - sparqlwrapper>=1.4.1
    - tolkein>=0.2.3
    - ujson>=3.0.0
  run:
    - biopython>=1.78
    - docopt>=0.6.2
    - elasticsearch>=7.8.1
    - filetype>=1.0.7
    - Pillow>=8.0
    - python
    - pyyaml
    - sparqlwrapper>=1.4.1
    - tolkein>=0.2.3
    - ujson>=3.0.0

test:
  imports:
    - genomehubs

about:
  home: "https://github.com/genomehubs/genomehubs"
  license: MIT
  license_family: MIT
  license_file:
  summary: "GenomeHubs"
  doc_url: https://genomehubs.readthedocs.io/
  dev_url:

extra:
  recipe-maintainers:
    - rjchallis
