common:
  directory: ~/genomehubs/demo
  docker-network: genomehubs-network
  es:
    host: localhost
    port: 9200
  taxonomy:
    taxdump: ~/genomehubs/demo/taxdump
    root: 7088
  version: v0.1
index:
  insdc:
    page-size: 1000
    genome-representation: full
  skip-validation: false
init:
  es:
    container: genomehubs-elasticsearch
    image: elasticsearch/elasticsearch-oss:7.6.2
    repository: docker.elastic.co
    startup-timeout: 30
    url: https://artifacts.elastic.co/downloads
  taxonomy:
    url: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
  use-docker: false
search: {}
