export const gridPropNames = new Set([
  "alignContent",
  "alignItems",
  "children",
  "classes",
  "className",
  "component",
  "container",
  "direction",
  "item",
  "justifyContent",
  "spacing",
  "wrap",
  "size",
  "offset",
]);
