name: flake8 Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: TrueBrain/actions-flake8@v2
        with:
          ignore: E203,E701,W503,W504,BLK100
          max_line_length: 118
          path: src
          plugins: flake8-black flake8-isort flake8-quotes
          error_classes: E,H,I00,Q00
