name: package-genomehubs-archive

on:
  workflow_dispatch:
    inputs:
      archive_version:
        description: 'Archive version to tag images with'
        required: true
        default: '2025.04.21'
      image:
        description: 'Which image to build: api, goat, or all'
        required: true
        default: 'api'

env:
  ARCHIVE_VERSION: ${{ github.event.inputs.archive_version }}

jobs:
  build-and-push-archive-api:
    if: ${{ github.event.inputs.image == 'api' || github.event.inputs.image == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: genomehubs/genomehubs-api
      - uses: actions/download-artifact@v4
        with:
          name: genomehubs-api-bundle
          path: ./src/genomehubs-api/build/
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/docker/api/Dockerfile
          push: true
          tags: |
            genomehubs/genomehubs-api:${{ env.ARCHIVE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-goat:
    if: ${{ github.event.inputs.image == 'goat' || github.event.inputs.image == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - id: latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: genomehubs/genomehubs
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: genomehubs/goat
      - name: Build and push GoaT image with content from repo
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/docker/ui/Dockerfile.site
          push: true
          build-args: |
            BASE_IMAGE=genomehubs/genomehubs-ui:${{ steps.latest-release.outputs.tag }}
            SITE_REPO=genomehubs/goat-ui
            SITE_BRANCH=main
            SITE_NAME=GoaT
            SITE_NAME_LONG=Genomes on a Tree
            GH_CITATION_URL=https://doi.org/10.12688/wellcomeopenres.18658.1
            GH_SUGGESTED_TERM=Canidae
            GH_TAXONOMY=ncbi
          tags: |
            genomehubs/goat:${{ env.ARCHIVE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
