name: package-genomehubs
env:
  VERSION: 2.4.7

on:
  push:

jobs:
  package-goat-ui:
    runs-on: ubuntu-latest
    needs:
      - create-github-release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: |
          git checkout goat-ui
          mv goat-ui/static src/client/static
          rm -r goat-ui
      - run: ./package-ui.sh
      - uses: actions/upload-artifact@v2
        with:
          name: goat-ui
          path: ./dist/*

  build-and-push-goat-ui:
    runs-on: ubuntu-latest
    needs: build-and-push-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: goat-ui
          path: ./dist
      - run: |
          mv dist/goat-ui/* src/docker/goat/
          rm -r dist/goat-ui
          ls src/docker/goat
          exit 1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/goat
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/docker/goat
          push: true
          tags: genomehubs/goat:${{ env.VERSION }}, genomehubs/goat:latest
          labels: ${{ steps.meta.outputs.labels }}
