name: package-genomehubs-latest

on: push

jobs:
  package-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-ui.sh
      - uses: actions/upload-artifact@v2
        with:
          name: genomehubs-ui
          path: ./dist/*

  package-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-api.sh
      - uses: actions/upload-artifact@v2
        with:
          name: genomehubs-api
          path: ./dist/*

  package-genomehubs-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: genomehubs
          path: ./dist/*

  package-goat-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: |
          git clone https://github.com/genomehubs/goat-ui
          mv goat-ui/static/* src/genomehubs-ui/src/client/static/
          rm -r goat-ui
      - run: ./package-ui.sh
      - uses: actions/upload-artifact@v2
        with:
          name: goat-ui
          path: ./dist/*

  build-and-push-genomehubs:
    runs-on: ubuntu-latest
    needs: package-genomehubs-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: genomehubs
          path: ./dist
      - run: |
          mv dist/*manylinux2014_x86_64.whl src/docker/
          rm -r dist/*
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/genomehubs
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/docker
          push: true
          tags: genomehubs/genomehubs:develop
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-api:
    runs-on: ubuntu-latest
    needs: package-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: genomehubs-api
          path: ./dist
      - run: |
          mv dist/genomehubs-api-linux src/docker/api/
          rm -r dist/*
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/genomehubs-api
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/docker/api
          push: true
          tags: genomehubs/genomehubs-api:develop
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-ui:
    runs-on: ubuntu-latest
    needs: package-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: genomehubs-ui
          path: ./dist
      - run: |
          mv dist/genomehubs-ui-linux src/docker/ui/
          rm -r dist/*
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/genomehubs-ui
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/docker/ui
          push: true
          tags: genomehubs/genomehubs-ui:develop
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-goat-ui:
    runs-on: ubuntu-latest
    needs: package-goat-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - uses: actions/download-artifact@v2
        with:
          name: goat-ui
          path: ./dist
      - run: |
          mv dist/genomehubs-ui-linux src/docker/goat/
          rm -r dist/*
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/goat
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/docker/goat
          push: true
          tags: genomehubs/goat:develop
          labels: ${{ steps.meta.outputs.labels }}
